// ── Learning Resources API ────────────────────────────────────
import api from './api';
import type {
  LearningResourcesAISettings,
  LessonNoteList,
  LessonNoteDetail,
  LessonNoteCreate,
  LessonNoteApprovalPayload,
  LessonNoteGrantAccessPayload,
  LessonMaterialList,
  LessonMaterialDetail,
  LessonMaterialCreate,
  MaterialSummary,
  FlashcardSetList,
  FlashcardSetDetail,
  AutoGeneratedQuizList,
  AutoGeneratedQuizDetail,
  LearningPathList,
  LearningPathDetail,
  LearningPathCreate,
  LearningPathSection,
  LearningPathSectionWrite,
  StudentMaterialProgress,
  StudentMaterialProgressUpdate,
  StudentLearningPathProgress,
  StudentBookmark,
  StudentBookmarkCreate,
  StudentHighlight,
  StudentHighlightCreate,
  StudentSharedNoteList,
  StudentSharedNoteDetail,
  StudentSharedNoteCreate,
  SharedNoteModerationPayload,
  TextToSpeechAudio,
  LiveClassSessionList,
  LiveClassSessionDetail,
  LiveClassSessionCreate,
  LiveClassJoinPayload,
  LiveClassJoinResponse,
  LiveClassAttendance,
  LiveClassWhiteboard,
  PendingNoteReminder,
  AIProcessingQueue,
  APIResponse,
  TaskDispatchResponse,
} from './types';


// ── AI Settings ───────────────────────────────────────────────

export const learningAISettingsAPI = {
  list: async (): Promise<LearningResourcesAISettings[]> => {
    const r = await api.get('/api/learning/ai-settings/');
    return r.data.results || r.data;
  },
  get: async (id: number): Promise<LearningResourcesAISettings> => {
    const r = await api.get(`/api/learning/ai-settings/${id}/`);
    return r.data;
  },
  getGlobal: async (): Promise<LearningResourcesAISettings | null> => {
    try {
      const r = await api.get('/api/learning/ai-settings/global/');
      return r.data.data;
    } catch (e: any) {
      if (e.response?.status === 404) return null;
      throw e;
    }
  },
  create: async (data: Partial<LearningResourcesAISettings>): Promise<LearningResourcesAISettings> => {
    const r = await api.post('/api/learning/ai-settings/', data);
     console.log(r)

    return r.data;

  },
  update: async (id: number, data: Partial<LearningResourcesAISettings>): Promise<LearningResourcesAISettings> => {
    const r = await api.patch(`/api/learning/ai-settings/${id}/`, data);
        console.log(r)

    return r.data;
  },
  delete: async (id: number): Promise<void> => {
    await api.delete(`/api/learning/ai-settings/${id}/`);
  },
};


// ── Lesson Notes ──────────────────────────────────────────────

export const lessonNotesAPI = {
  list: async (params?: {
    subject?: number;
    status?: string;
    session?: number;
    term?: number;
  }): Promise<LessonNoteList[]> => {
    const r = await api.get('/api/learning/notes/', { params });
    return r.data.results || r.data;
  },
  get: async (id: number): Promise<LessonNoteDetail> => {
    const r = await api.get(`/api/learning/notes/${id}/`);
    return r.data;
  },
  create: async (data: LessonNoteCreate): Promise<LessonNoteDetail> => {
    const formData = new FormData();
    Object.entries(data).forEach(([key, value]) => {
      if (value === null || value === undefined) return;
      if (Array.isArray(value)) {
        value.forEach((v) => formData.append(key, String(v)));
      } else if (value instanceof File) {
        formData.append(key, value);
      } else {
        formData.append(key, String(value));
      }
    });
    const r = await api.post('/api/learning/notes/', formData, {
      headers: { 'Content-Type': 'multipart/form-data' },
    });
    return r.data;
  },
  update: async (id: number, data: Partial<LessonNoteCreate>): Promise<LessonNoteDetail> => {
    const r = await api.patch(`/api/learning/notes/${id}/`, data);
    return r.data;
  },
  delete: async (id: number): Promise<void> => {
    await api.delete(`/api/learning/notes/${id}/`);
  },
  submit: async (id: number): Promise<APIResponse> => {
    const r = await api.post(`/api/learning/notes/${id}/submit/`);
    return r.data;
  },
  review: async (id: number, data: LessonNoteApprovalPayload): Promise<APIResponse> => {
    const r = await api.post(`/api/learning/notes/${id}/review/`, data);
    return r.data;
  },
  toggleAccess: async (id: number, data: LessonNoteGrantAccessPayload): Promise<APIResponse> => {
    const r = await api.post(`/api/learning/notes/${id}/access/`, data);
    return r.data;
  },
  downloadPdf: async (id: number): Promise<Blob> => {
    const r = await api.get(`/api/learning/notes/${id}/pdf/`, {
      responseType: 'blob',
    });
    return r.data;
  },
  generateAI: async (id: number): Promise<APIResponse<TaskDispatchResponse>> => {
    const r = await api.post(`/api/learning/notes/${id}/generate-ai/`);
    return r.data;
  },
  generateSummary: async (id: number): Promise<APIResponse<TaskDispatchResponse>> => {
    const r = await api.post(`/api/learning/notes/${id}/generate-summary/`);
    return r.data;
  },
  generateTTS: async (id: number): Promise<APIResponse<TaskDispatchResponse>> => {
    const r = await api.post(`/api/learning/notes/${id}/generate-tts/`);
    return r.data;
  },
  previewReview: async (data: {
  content: string;
  school_section?: number | null;
}): Promise<APIResponse<{
  overall_score: number;
  feedback: string;
  suggestions: string[];
  checks: Record<string, { score: number; comment: string }>;
  passed: boolean;
  threshold: number;
}>> => {
  const r = await api.post('/api/learning/notes/preview-review/', data);
  return r.data;
},
};


// ── Lesson Materials ──────────────────────────────────────────

export const lessonMaterialsAPI = {
  list: async (params?: {
    subject?: number;
    type?: string;
    processing_status?: string;
    lesson_note?: number;
  }): Promise<LessonMaterialList[]> => {
    const r = await api.get('/api/learning/materials/', { params });
    return r.data.results || r.data;
  },
  get: async (id: number): Promise<LessonMaterialDetail> => {
    const r = await api.get(`/api/learning/materials/${id}/`);
    return r.data;
  },
  create: async (data: LessonMaterialCreate): Promise<LessonMaterialDetail> => {
    const formData = new FormData();
    Object.entries(data).forEach(([key, value]) => {
      if (value === null || value === undefined) return;
      if (Array.isArray(value)) {
        value.forEach((v) => formData.append(key, String(v)));
      } else if (value instanceof File) {
        formData.append(key, value);
      } else {
        formData.append(key, String(value));
      }
    });
    const r = await api.post('/api/learning/materials/', formData, {
      headers: { 'Content-Type': 'multipart/form-data' },
    });
    return r.data;
  },
  update: async (id: number, data: Partial<LessonMaterialCreate>): Promise<LessonMaterialDetail> => {
    const r = await api.patch(`/api/learning/materials/${id}/`, data);
    return r.data;
  },
  delete: async (id: number): Promise<void> => {
    await api.delete(`/api/learning/materials/${id}/`);
  },
  generateSummary: async (id: number): Promise<APIResponse<TaskDispatchResponse>> => {
    const r = await api.post(`/api/learning/materials/${id}/generate-summary/`);
    return r.data;
  },
};


// ── Summaries ─────────────────────────────────────────────────

export const materialSummariesAPI = {
  list: async (params?: {
    material?: number;
    lesson_note?: number;
  }): Promise<MaterialSummary[]> => {
    const r = await api.get('/api/learning/summaries/', { params });
    return r.data.results || r.data;
  },
  get: async (id: number): Promise<MaterialSummary> => {
    const r = await api.get(`/api/learning/summaries/${id}/`);
    return r.data;
  },
};


// ── Flashcard Sets ────────────────────────────────────────────

export const flashcardSetsAPI = {
  list: async (params?: { subject?: number }): Promise<FlashcardSetList[]> => {
    const r = await api.get('/api/learning/flashcard-sets/', { params });
    return r.data.results || r.data;
  },
  get: async (id: number): Promise<FlashcardSetDetail> => {
    const r = await api.get(`/api/learning/flashcard-sets/${id}/`);
    return r.data;
  },
};


// ── Auto Generated Quizzes ────────────────────────────────────

export const autoQuizzesAPI = {
  list: async (params?: { subject?: number }): Promise<AutoGeneratedQuizList[]> => {
    const r = await api.get('/api/learning/quizzes/', { params });
    return r.data.results || r.data;
  },
  get: async (id: number): Promise<AutoGeneratedQuizDetail> => {
    const r = await api.get(`/api/learning/quizzes/${id}/`);
    return r.data;
  },
};


// ── Learning Paths ────────────────────────────────────────────

export const learningPathsAPI = {
  list: async (params?: { subject?: number }): Promise<LearningPathList[]> => {
    const r = await api.get('/api/learning/paths/', { params });
    return r.data.results || r.data;
  },
  get: async (id: number): Promise<LearningPathDetail> => {
    const r = await api.get(`/api/learning/paths/${id}/`);
    return r.data;
  },
  create: async (data: LearningPathCreate): Promise<LearningPathDetail> => {
    const r = await api.post('/api/learning/paths/', data);
    return r.data;
  },
  update: async (id: number, data: Partial<LearningPathCreate>): Promise<LearningPathDetail> => {
    const r = await api.patch(`/api/learning/paths/${id}/`, data);
    return r.data;
  },
  delete: async (id: number): Promise<void> => {
    await api.delete(`/api/learning/paths/${id}/`);
  },
  suggestSections: async (id: number): Promise<APIResponse<TaskDispatchResponse>> => {
    const r = await api.post(`/api/learning/paths/${id}/suggest-sections/`);
    return r.data;
  },
  acceptAISections: async (id: number): Promise<APIResponse> => {
    const r = await api.post(`/api/learning/paths/${id}/accept-ai-sections/`);
    return r.data;
  },
  rejectAISections: async (id: number): Promise<APIResponse> => {
    const r = await api.delete(`/api/learning/paths/${id}/reject-ai-sections/`);
    return r.data;
  },
};


// ── Learning Path Sections ────────────────────────────────────

export const pathSectionsAPI = {
  list: async (params?: { learning_path?: number }): Promise<LearningPathSection[]> => {
    const r = await api.get('/api/learning/path-sections/', { params });
    return r.data.results || r.data;
  },
  get: async (id: number): Promise<LearningPathSection> => {
    const r = await api.get(`/api/learning/path-sections/${id}/`);
    return r.data;
  },
  create: async (data: LearningPathSectionWrite): Promise<LearningPathSection> => {
    const r = await api.post('/api/learning/path-sections/', data);
    return r.data;
  },
  update: async (id: number, data: Partial<LearningPathSectionWrite>): Promise<LearningPathSection> => {
    const r = await api.patch(`/api/learning/path-sections/${id}/`, data);
    return r.data;
  },
  delete: async (id: number): Promise<void> => {
    await api.delete(`/api/learning/path-sections/${id}/`);
  },
};


// ── Student Material Progress ─────────────────────────────────

export const materialProgressAPI = {
  list: async (params?: { material?: number }): Promise<StudentMaterialProgress[]> => {
    const r = await api.get('/api/learning/material-progress/', { params });
    return r.data.results || r.data;
  },
  get: async (id: number): Promise<StudentMaterialProgress> => {
    const r = await api.get(`/api/learning/material-progress/${id}/`);
    return r.data;
  },
  create: async (data: { material: number }): Promise<StudentMaterialProgress> => {
    const r = await api.post('/api/learning/material-progress/', data);
    return r.data;
  },
  update: async (id: number, data: StudentMaterialProgressUpdate): Promise<StudentMaterialProgress> => {
    const r = await api.patch(`/api/learning/material-progress/${id}/`, data);
    return r.data;
  },
  markStarted: async (id: number): Promise<APIResponse> => {
    const r = await api.post(`/api/learning/material-progress/${id}/mark-started/`);
    return r.data;
  },
  markCompleted: async (id: number): Promise<APIResponse> => {
    const r = await api.post(`/api/learning/material-progress/${id}/mark-completed/`);
    return r.data;
  },
  updatePosition: async (data: {
    material_id: number;
    last_position_seconds?: number;
    time_spent_seconds?: number;
    percentage_completed?: number;
  }): Promise<APIResponse> => {
    const r = await api.post('/api/learning/material-progress/update-position/', data);
    return r.data;
  },
};


// ── Student Learning Path Progress ────────────────────────────

export const pathProgressAPI = {
  list: async (): Promise<StudentLearningPathProgress[]> => {
    const r = await api.get('/api/learning/path-progress/');
    return r.data.results || r.data;
  },
  get: async (id: number): Promise<StudentLearningPathProgress> => {
    const r = await api.get(`/api/learning/path-progress/${id}/`);
    return r.data;
  },
  enroll: async (learning_path_id: number): Promise<APIResponse<StudentLearningPathProgress>> => {
    const r = await api.post('/api/learning/path-progress/enroll/', { learning_path_id });
    return r.data;
  },
  unlockNext: async (id: number): Promise<APIResponse<StudentLearningPathProgress>> => {
    const r = await api.post(`/api/learning/path-progress/${id}/unlock-next/`);
    return r.data;
  },
};


// ── Bookmarks ─────────────────────────────────────────────────

export const bookmarksAPI = {
  list: async (): Promise<StudentBookmark[]> => {
    const r = await api.get('/api/learning/bookmarks/');
    return r.data.results || r.data;
  },
  get: async (id: number): Promise<StudentBookmark> => {
    const r = await api.get(`/api/learning/bookmarks/${id}/`);
    return r.data;
  },
  create: async (data: StudentBookmarkCreate): Promise<StudentBookmark> => {
    const r = await api.post('/api/learning/bookmarks/', data);
    return r.data;
  },
  update: async (id: number, data: Partial<StudentBookmarkCreate>): Promise<StudentBookmark> => {
    const r = await api.patch(`/api/learning/bookmarks/${id}/`, data);
    return r.data;
  },
  delete: async (id: number): Promise<void> => {
    await api.delete(`/api/learning/bookmarks/${id}/`);
  },
};


// ── Highlights ────────────────────────────────────────────────

export const highlightsAPI = {
  list: async (params?: { lesson_note?: number }): Promise<StudentHighlight[]> => {
    const r = await api.get('/api/learning/highlights/', { params });
    return r.data.results || r.data;
  },
  get: async (id: number): Promise<StudentHighlight> => {
    const r = await api.get(`/api/learning/highlights/${id}/`);
    return r.data;
  },
  create: async (data: StudentHighlightCreate): Promise<StudentHighlight> => {
    const r = await api.post('/api/learning/highlights/', data);
    return r.data;
  },
  update: async (id: number, data: Partial<StudentHighlightCreate>): Promise<StudentHighlight> => {
    const r = await api.patch(`/api/learning/highlights/${id}/`, data);
    return r.data;
  },
  delete: async (id: number): Promise<void> => {
    await api.delete(`/api/learning/highlights/${id}/`);
  },
};


// ── Shared Notes ──────────────────────────────────────────────

export const sharedNotesAPI = {
  list: async (params?: { subject?: number; status?: string }): Promise<StudentSharedNoteList[]> => {
    const r = await api.get('/api/learning/shared-notes/', { params });
    return r.data.results || r.data;
  },
  get: async (id: number): Promise<StudentSharedNoteDetail> => {
    const r = await api.get(`/api/learning/shared-notes/${id}/`);
    return r.data;
  },
  create: async (data: StudentSharedNoteCreate): Promise<StudentSharedNoteDetail> => {
    const r = await api.post('/api/learning/shared-notes/', data);
    return r.data;
  },
  update: async (id: number, data: Partial<StudentSharedNoteCreate>): Promise<StudentSharedNoteDetail> => {
    const r = await api.patch(`/api/learning/shared-notes/${id}/`, data);
    return r.data;
  },
  delete: async (id: number): Promise<void> => {
    await api.delete(`/api/learning/shared-notes/${id}/`);
  },
  moderate: async (id: number, data: SharedNoteModerationPayload): Promise<APIResponse> => {
    const r = await api.post(`/api/learning/shared-notes/${id}/moderate/`, data);
    return r.data;
  },
  like: async (id: number): Promise<APIResponse> => {
    const r = await api.post(`/api/learning/shared-notes/${id}/like/`);
    return r.data;
  },
  recordView: async (id: number): Promise<APIResponse> => {
    const r = await api.post(`/api/learning/shared-notes/${id}/view/`);
    return r.data;
  },
};


// ── TTS Audio ─────────────────────────────────────────────────

export const ttsAudioAPI = {
  list: async (params?: { lesson_note?: number }): Promise<TextToSpeechAudio[]> => {
    const r = await api.get('/api/learning/tts-audio/', { params });
    return r.data.results || r.data;
  },
  get: async (id: number): Promise<TextToSpeechAudio> => {
    const r = await api.get(`/api/learning/tts-audio/${id}/`);
    return r.data;
  },
};


// ── Live Classes ──────────────────────────────────────────────

export const liveClassesAPI = {
  list: async (params?: { status?: string }): Promise<LiveClassSessionList[]> => {
    const r = await api.get('/api/learning/live-classes/', { params });
    return r.data.results || r.data;
  },
  get: async (id: number): Promise<LiveClassSessionDetail> => {
    const r = await api.get(`/api/learning/live-classes/${id}/`);
    return r.data;
  },
  create: async (data: LiveClassSessionCreate): Promise<LiveClassSessionDetail> => {
    const r = await api.post('/api/learning/live-classes/', data);
    return r.data;
  },
  update: async (id: number, data: Partial<LiveClassSessionCreate>): Promise<LiveClassSessionDetail> => {
    const r = await api.patch(`/api/learning/live-classes/${id}/`, data);
    return r.data;
  },
  delete: async (id: number): Promise<void> => {
    await api.delete(`/api/learning/live-classes/${id}/`);
  },
  start: async (id: number): Promise<APIResponse<LiveClassSessionDetail>> => {
    const r = await api.post(`/api/learning/live-classes/${id}/start/`);
    return r.data;
  },
  end: async (id: number): Promise<APIResponse> => {
    const r = await api.post(`/api/learning/live-classes/${id}/end/`);
    return r.data;
  },
  join: async (id: number, data?: LiveClassJoinPayload): Promise<APIResponse<LiveClassJoinResponse>> => {
    const r = await api.post(`/api/learning/live-classes/${id}/join/`, data || {});
    return r.data;
  },
  leave: async (id: number): Promise<APIResponse> => {
    const r = await api.post(`/api/learning/live-classes/${id}/leave/`);
    return r.data;
  },
  saveWhiteboard: async (id: number, data: {
    whiteboard_data: Record<string, unknown>;
    title?: string;
  }): Promise<APIResponse<LiveClassWhiteboard>> => {
    const r = await api.post(`/api/learning/live-classes/${id}/save-whiteboard/`, data);
    return r.data;
  },
  getAttendance: async (id: number): Promise<APIResponse<LiveClassAttendance[]>> => {
    const r = await api.get(`/api/learning/live-classes/${id}/attendance/`);
    return r.data;
  },
};


// ── Attendance ────────────────────────────────────────────────

export const liveClassAttendanceAPI = {
  list: async (params?: { live_class?: number }): Promise<LiveClassAttendance[]> => {
    const r = await api.get('/api/learning/attendance/', { params });
    return r.data.results || r.data;
  },
  get: async (id: number): Promise<LiveClassAttendance> => {
    const r = await api.get(`/api/learning/attendance/${id}/`);
    return r.data;
  },
};


// ── Whiteboards ───────────────────────────────────────────────

export const whiteboardsAPI = {
  list: async (params?: { live_class?: number }): Promise<LiveClassWhiteboard[]> => {
    const r = await api.get('/api/learning/whiteboards/', { params });
    return r.data.results || r.data;
  },
  get: async (id: number): Promise<LiveClassWhiteboard> => {
    const r = await api.get(`/api/learning/whiteboards/${id}/`);
    return r.data;
  },
};


// ── Reminders ─────────────────────────────────────────────────

export const noteRemindersAPI = {
  list: async (): Promise<PendingNoteReminder[]> => {
    const r = await api.get('/api/learning/reminders/');
    return r.data.results || r.data;
  },
  get: async (id: number): Promise<PendingNoteReminder> => {
    const r = await api.get(`/api/learning/reminders/${id}/`);
    return r.data;
  },
  acknowledge: async (id: number): Promise<APIResponse> => {
    const r = await api.post(`/api/learning/reminders/${id}/acknowledge/`);
    return r.data;
  },
};


// ── AI Processing Queue ───────────────────────────────────────

export const aiQueueAPI = {
  list: async (params?: {
    status?: string;
    task_type?: string;
  }): Promise<AIProcessingQueue[]> => {
    const r = await api.get('/api/learning/queue/', { params });
    return r.data.results || r.data;
  },
  get: async (id: number): Promise<AIProcessingQueue> => {
    const r = await api.get(`/api/learning/queue/${id}/`);
    return r.data;
  },
  summary: async (): Promise<Record<string, number>> => {
    const r = await api.get('/api/learning/queue/summary/');
    return r.data.data;
  },
};