import api from './api';
import type {
  // Phase 1 (MVP)
  LearningResourcesSettings,
  LessonNoteList,
  LessonNoteDetail,
  LessonNoteCreate,
  LessonNoteApprovalPayload,
  LessonNoteGrantAccessPayload,
  LessonNotePreviewReviewResponse,
  LessonMaterialList,
  LessonMaterialDetail,
  LessonMaterialCreate,
  MaterialSummary,
  FlashcardSetList,
  FlashcardSetDetail,
  AutoGeneratedQuizList,
  AutoGeneratedQuizDetail,
  SchemeOfWorkList,
  SchemeOfWorkDetail,
  SchemeOfWorkCreate,
  SchemeOfWorkApprovalPayload,
  SchemeOfWorkWeek,
  PendingNoteReminder,
  TextToSpeechAudio,

  // Phase 2
  LearningPathList,
  LearningPathDetail,
  LearningPathCreate,
  LearningPathSection,
  LearningPathSectionWrite,
  StudentMaterialProgress,
  StudentMaterialProgressUpdate,
  StudentLearningPathProgress,
  StudentBookmark,
  StudentBookmarkCreate,
  StudentHighlight,
  StudentHighlightCreate,
  StudentSharedNoteList,
  StudentSharedNoteDetail,
  StudentSharedNoteCreate,
  SharedNoteModerationPayload,
  LessonAssignmentList,
  LessonAssignmentDetail,
  LessonAssignmentCreate,
  StudentAssignmentSubmission,
  StudentAssignmentSubmissionCreate,
  SubmissionGradePayload,
  LiveClassSessionList,
  LiveClassSessionDetail,
  LiveClassSessionCreate,
  LiveClassJoinPayload,
  LiveClassJoinResponse,
  LiveClassAttendance,
  LiveClassWhiteboard,
  StudentScreenMonitor,
  ScreenMonitorFlagPayload,
  LiveClassPenStream,
  SmartPenDevice,
  HandwritingCapture,

  // Infrastructure
  AIProcessingQueue,
  APIResponse,
  TaskDispatchResponse,
} from './types';

const BASE_URL = '/api/learning';

// ============================================================
// PHASE 1: CORE MVP (CURRICULUM & CONTENT)
// ============================================================

// ── AI Settings ───────────────────────────────────────────────

export const learningAISettingsAPI = {
  list: async (): Promise<LearningResourcesSettings[]> => {
    const r = await api.get(`${BASE_URL}/ai-settings/`);
    return r.data.results || r.data;
  },
  get: async (id: number): Promise<LearningResourcesSettings> => {
    const r = await api.get(`${BASE_URL}/ai-settings/${id}/`);
    return r.data;
  },
  getGlobal: async (): Promise<LearningResourcesSettings | null> => {
    try {
      const r = await api.get(`${BASE_URL}/ai-settings/global/`);
      return r.data.data;
    } catch (e: any) {
      if (e.response?.status === 404) return null;
      throw e;
    }
  },
  create: async (data: Partial<LearningResourcesSettings>): Promise<LearningResourcesSettings> => {
    const r = await api.post(`${BASE_URL}/ai-settings/`, data);
    return r.data;
  },
  update: async (id: number, data: Partial<LearningResourcesSettings>): Promise<LearningResourcesSettings> => {
    const r = await api.patch(`${BASE_URL}/ai-settings/${id}/`, data);
    return r.data;
  },
  delete: async (id: number): Promise<void> => {
    await api.delete(`${BASE_URL}/ai-settings/${id}/`);
  },
};

// ── Scheme of Work ────────────────────────────────────────────

export const schemeOfWorkAPI = {
  list: async (params?: { subject?: number; status?: string }): Promise<SchemeOfWorkList[]> => {
    const r = await api.get(`${BASE_URL}/schemes/`, { params });
    return r.data.results || r.data;
  },
  get: async (id: number): Promise<SchemeOfWorkDetail> => {
    const r = await api.get(`${BASE_URL}/schemes/${id}/`);
    return r.data;
  },
  create: async (data: SchemeOfWorkCreate): Promise<SchemeOfWorkDetail> => {
    const r = await api.post(`${BASE_URL}/schemes/`, data);
    return r.data;
  },
  update: async (id: number, data: Partial<SchemeOfWorkCreate>): Promise<SchemeOfWorkDetail> => {
    const r = await api.patch(`${BASE_URL}/schemes/${id}/`, data);
    return r.data;
  },
  delete: async (id: number): Promise<void> => {
    await api.delete(`${BASE_URL}/schemes/${id}/`);
  },
  submit: async (id: number): Promise<APIResponse> => {
    const r = await api.post(`${BASE_URL}/schemes/${id}/submit/`);
    return r.data;
  },
  review: async (id: number, data: SchemeOfWorkApprovalPayload): Promise<APIResponse> => {
    const r = await api.post(`${BASE_URL}/schemes/${id}/review/`, data);
    return r.data;
  },
};

export const schemeWeeksAPI = {
  list: async (params?: { scheme_of_work?: number }): Promise<SchemeOfWorkWeek[]> => {
    const r = await api.get(`${BASE_URL}/scheme-weeks/`, { params });
    return r.data.results || r.data;
  },
  get: async (id: number): Promise<SchemeOfWorkWeek> => {
    const r = await api.get(`${BASE_URL}/scheme-weeks/${id}/`);
    return r.data;
  },
  create: async (data: Partial<SchemeOfWorkWeek>): Promise<SchemeOfWorkWeek> => {
    const r = await api.post(`${BASE_URL}/scheme-weeks/`, data);
    return r.data;
  },
  update: async (id: number, data: Partial<SchemeOfWorkWeek>): Promise<SchemeOfWorkWeek> => {
    const r = await api.patch(`${BASE_URL}/scheme-weeks/${id}/`, data);
    return r.data;
  },
  delete: async (id: number): Promise<void> => {
    await api.delete(`${BASE_URL}/scheme-weeks/${id}/`);
  },
};

// ── Lesson Notes ──────────────────────────────────────────────

export const lessonNotesAPI = {
  list: async (params?: {
    subject?: number;
    status?: string;
    session?: number;
    term?: number;
  }): Promise<LessonNoteList[]> => {
    const r = await api.get(`${BASE_URL}/notes/`, { params });
    return r.data.results || r.data;
  },
  get: async (id: number): Promise<LessonNoteDetail> => {
    const r = await api.get(`${BASE_URL}/notes/${id}/`);
    return r.data;
  },
  create: async (data: LessonNoteCreate): Promise<LessonNoteDetail> => {
    const formData = new FormData();
    Object.entries(data).forEach(([key, value]) => {
      if (value === null || value === undefined) return;
      if (Array.isArray(value)) {
        value.forEach((v) => formData.append(key, String(v)));
      } else if (value instanceof File) {
        formData.append(key, value);
      } else {
        formData.append(key, String(value));
      }
    });
    const r = await api.post(`${BASE_URL}/notes/`, formData, {
      headers: { 'Content-Type': 'multipart/form-data' },
    });
    return r.data;
  },
  update: async (id: number, data: Partial<LessonNoteCreate>): Promise<LessonNoteDetail> => {
    const formData = new FormData();
    Object.entries(data).forEach(([key, value]) => {
      if (value === null || value === undefined) return;
      if (Array.isArray(value)) {
        value.forEach((v) => formData.append(key, String(v)));
      } else if (value instanceof File) {
        formData.append(key, value);
      } else {
        formData.append(key, String(value));
      }
    });
    const r = await api.patch(`${BASE_URL}/notes/${id}/`, formData, {
      headers: { 'Content-Type': 'multipart/form-data' },
    });
    return r.data;
  },
  delete: async (id: number): Promise<void> => {
    await api.delete(`${BASE_URL}/notes/${id}/`);
  },
  submit: async (id: number): Promise<APIResponse> => {
    const r = await api.post(`${BASE_URL}/notes/${id}/submit/`);
    return r.data;
  },
  review: async (id: number, data: LessonNoteApprovalPayload): Promise<APIResponse> => {
    const r = await api.post(`${BASE_URL}/notes/${id}/review/`, data);
    return r.data;
  },
  toggleAccess: async (id: number, data: LessonNoteGrantAccessPayload): Promise<APIResponse> => {
    const r = await api.post(`${BASE_URL}/notes/${id}/access/`, data);
    return r.data;
  },
  downloadPdf: async (id: number): Promise<Blob> => {
    const r = await api.get(`${BASE_URL}/notes/${id}/pdf/`, {
      responseType: 'blob',
    });
    return r.data;
  },
  generateAI: async (id: number): Promise<APIResponse<TaskDispatchResponse>> => {
    const r = await api.post(`${BASE_URL}/notes/${id}/generate-ai/`);
    return r.data;
  },
  generateSummary: async (id: number): Promise<APIResponse<TaskDispatchResponse>> => {
    const r = await api.post(`${BASE_URL}/notes/${id}/generate-summary/`);
    return r.data;
  },
  generateTTS: async (id: number): Promise<APIResponse<TaskDispatchResponse>> => {
    const r = await api.post(`${BASE_URL}/notes/${id}/generate-tts/`);
    return r.data;
  },
  previewReview: async (data: {
    content: string;
    school_section?: number | null;
  }): Promise<APIResponse<LessonNotePreviewReviewResponse>> => {
    const r = await api.post(`${BASE_URL}/notes/preview-review/`, data);
    return r.data;
  },
};

// ── Lesson Materials ──────────────────────────────────────────

export const lessonMaterialsAPI = {
  list: async (params?: {
    subject?: number;
    type?: string;
    processing_status?: string;
    lesson_note?: number;
  }): Promise<LessonMaterialList[]> => {
    const r = await api.get(`${BASE_URL}/materials/`, { params });
    return r.data.results || r.data;
  },
  get: async (id: number): Promise<LessonMaterialDetail> => {
    const r = await api.get(`${BASE_URL}/materials/${id}/`);
    return r.data;
  },
  create: async (data: LessonMaterialCreate): Promise<LessonMaterialDetail> => {
    const formData = new FormData();
    Object.entries(data).forEach(([key, value]) => {
      if (value === null || value === undefined) return;
      if (Array.isArray(value)) {
        value.forEach((v) => formData.append(key, String(v)));
      } else if (value instanceof File) {
        formData.append(key, value);
      } else {
        formData.append(key, String(value));
      }
    });
    const r = await api.post(`${BASE_URL}/materials/`, formData, {
      headers: { 'Content-Type': 'multipart/form-data' },
    });
    return r.data;
  },
  update: async (id: number, data: Partial<LessonMaterialCreate>): Promise<LessonMaterialDetail> => {
    const formData = new FormData();
    Object.entries(data).forEach(([key, value]) => {
      if (value === null || value === undefined) return;
      if (Array.isArray(value)) {
        value.forEach((v) => formData.append(key, String(v)));
      } else if (value instanceof File) {
        formData.append(key, value);
      } else {
        formData.append(key, String(value));
      }
    });
    const r = await api.patch(`${BASE_URL}/materials/${id}/`, formData, {
      headers: { 'Content-Type': 'multipart/form-data' },
    });
    return r.data;
  },
  delete: async (id: number): Promise<void> => {
    await api.delete(`${BASE_URL}/materials/${id}/`);
  },
  generateSummary: async (id: number): Promise<APIResponse<TaskDispatchResponse>> => {
    const r = await api.post(`${BASE_URL}/materials/${id}/generate-summary/`);
    return r.data;
  },
};

// ── Summaries & Flashcards & Quizzes ──────────────────────────

export const materialSummariesAPI = {
  list: async (params?: { material?: number; lesson_note?: number }): Promise<MaterialSummary[]> => {
    const r = await api.get(`${BASE_URL}/summaries/`, { params });
    return r.data.results || r.data;
  },
  get: async (id: number): Promise<MaterialSummary> => {
    const r = await api.get(`${BASE_URL}/summaries/${id}/`);
    return r.data;
  },
};

export const flashcardSetsAPI = {
  list: async (params?: { subject?: number }): Promise<FlashcardSetList[]> => {
    const r = await api.get(`${BASE_URL}/flashcard-sets/`, { params });
    return r.data.results || r.data;
  },
  get: async (id: number): Promise<FlashcardSetDetail> => {
    const r = await api.get(`${BASE_URL}/flashcard-sets/${id}/`);
    return r.data;
  },
};

export const autoQuizzesAPI = {
  list: async (params?: { subject?: number }): Promise<AutoGeneratedQuizList[]> => {
    const r = await api.get(`${BASE_URL}/quizzes/`, { params });
    return r.data.results || r.data;
  },
  get: async (id: number): Promise<AutoGeneratedQuizDetail> => {
    const r = await api.get(`${BASE_URL}/quizzes/${id}/`);
    return r.data;
  },
};

export const ttsAudioAPI = {
  list: async (params?: { lesson_note?: number }): Promise<TextToSpeechAudio[]> => {
    const r = await api.get(`${BASE_URL}/tts-audio/`, { params });
    return r.data.results || r.data;
  },
  get: async (id: number): Promise<TextToSpeechAudio> => {
    const r = await api.get(`${BASE_URL}/tts-audio/${id}/`);
    return r.data;
  },
};

// ── Reminders ─────────────────────────────────────────────────

export const noteRemindersAPI = {
  list: async (): Promise<PendingNoteReminder[]> => {
    const r = await api.get(`${BASE_URL}/reminders/`);
    return r.data.results || r.data;
  },
  get: async (id: number): Promise<PendingNoteReminder> => {
    const r = await api.get(`${BASE_URL}/reminders/${id}/`);
    return r.data;
  },
  acknowledge: async (id: number): Promise<APIResponse> => {
    const r = await api.post(`${BASE_URL}/reminders/${id}/acknowledge/`);
    return r.data;
  },
};

// ============================================================
// PHASE 2: ADVANCED ECOSYSTEM
// ============================================================

// ── Assignments ───────────────────────────────────────────────

export const assignmentsAPI = {
  list: async (params?: { subject?: number }): Promise<LessonAssignmentList[]> => {
    const r = await api.get(`${BASE_URL}/assignments/`, { params });
    return r.data.results || r.data;
  },
  get: async (id: number): Promise<LessonAssignmentDetail> => {
    const r = await api.get(`${BASE_URL}/assignments/${id}/`);
    return r.data;
  },
  create: async (data: LessonAssignmentCreate): Promise<LessonAssignmentDetail> => {
    const formData = new FormData();
    Object.entries(data).forEach(([key, value]) => {
      if (value === null || value === undefined) return;
      if (Array.isArray(value)) {
        value.forEach((v) => formData.append(key, String(v)));
      } else if (value instanceof File) {
        formData.append(key, value);
      } else {
        formData.append(key, String(value));
      }
    });
    const r = await api.post(`${BASE_URL}/assignments/`, formData, {
      headers: { 'Content-Type': 'multipart/form-data' },
    });
    return r.data;
  },
  update: async (id: number, data: Partial<LessonAssignmentCreate>): Promise<LessonAssignmentDetail> => {
    const formData = new FormData();
    Object.entries(data).forEach(([key, value]) => {
      if (value === null || value === undefined) return;
      if (Array.isArray(value)) {
        value.forEach((v) => formData.append(key, String(v)));
      } else if (value instanceof File) {
        formData.append(key, value);
      } else {
        formData.append(key, String(value));
      }
    });
    const r = await api.patch(`${BASE_URL}/assignments/${id}/`, formData, {
      headers: { 'Content-Type': 'multipart/form-data' },
    });
    return r.data;
  },
  delete: async (id: number): Promise<void> => {
    await api.delete(`${BASE_URL}/assignments/${id}/`);
  },
};

export const assignmentSubmissionsAPI = {
  list: async (): Promise<StudentAssignmentSubmission[]> => {
    const r = await api.get(`${BASE_URL}/assignment-submissions/`);
    return r.data.results || r.data;
  },
  get: async (id: number): Promise<StudentAssignmentSubmission> => {
    const r = await api.get(`${BASE_URL}/assignment-submissions/${id}/`);
    return r.data;
  },
  create: async (assignmentId: number, data: StudentAssignmentSubmissionCreate): Promise<StudentAssignmentSubmission> => {
    const formData = new FormData();
    formData.append('assignment', String(assignmentId));
    if (data.submission_text) formData.append('submission_text', data.submission_text);
    if (data.submission_file) formData.append('submission_file', data.submission_file);

    const r = await api.post(`${BASE_URL}/assignment-submissions/`, formData, {
      headers: { 'Content-Type': 'multipart/form-data' },
    });
    return r.data;
  },
  grade: async (id: number, data: SubmissionGradePayload): Promise<APIResponse<StudentAssignmentSubmission>> => {
    const r = await api.post(`${BASE_URL}/assignment-submissions/${id}/grade/`, data);
    return r.data;
  },
};

// ── Learning Paths ────────────────────────────────────────────

export const learningPathsAPI = {
  list: async (params?: { subject?: number }): Promise<LearningPathList[]> => {
    const r = await api.get(`${BASE_URL}/paths/`, { params });
    return r.data.results || r.data;
  },
  get: async (id: number): Promise<LearningPathDetail> => {
    const r = await api.get(`${BASE_URL}/paths/${id}/`);
    return r.data;
  },
  create: async (data: LearningPathCreate): Promise<LearningPathDetail> => {
    const r = await api.post(`${BASE_URL}/paths/`, data);
    return r.data;
  },
  update: async (id: number, data: Partial<LearningPathCreate>): Promise<LearningPathDetail> => {
    const r = await api.patch(`${BASE_URL}/paths/${id}/`, data);
    return r.data;
  },
  delete: async (id: number): Promise<void> => {
    await api.delete(`${BASE_URL}/paths/${id}/`);
  },
  suggestSections: async (id: number): Promise<APIResponse<TaskDispatchResponse>> => {
    const r = await api.post(`${BASE_URL}/paths/${id}/suggest-sections/`);
    return r.data;
  },
  acceptAISections: async (id: number): Promise<APIResponse> => {
    const r = await api.post(`${BASE_URL}/paths/${id}/accept-ai-sections/`);
    return r.data;
  },
  rejectAISections: async (id: number): Promise<APIResponse> => {
    const r = await api.delete(`${BASE_URL}/paths/${id}/reject-ai-sections/`);
    return r.data;
  },
};

export const pathSectionsAPI = {
  list: async (params?: { learning_path?: number }): Promise<LearningPathSection[]> => {
    const r = await api.get(`${BASE_URL}/path-sections/`, { params });
    return r.data.results || r.data;
  },
  get: async (id: number): Promise<LearningPathSection> => {
    const r = await api.get(`${BASE_URL}/path-sections/${id}/`);
    return r.data;
  },
  create: async (data: LearningPathSectionWrite): Promise<LearningPathSection> => {
    const r = await api.post(`${BASE_URL}/path-sections/`, data);
    return r.data;
  },
  update: async (id: number, data: Partial<LearningPathSectionWrite>): Promise<LearningPathSection> => {
    const r = await api.patch(`${BASE_URL}/path-sections/${id}/`, data);
    return r.data;
  },
  delete: async (id: number): Promise<void> => {
    await api.delete(`${BASE_URL}/path-sections/${id}/`);
  },
};

export const materialProgressAPI = {
  list: async (params?: { material?: number }): Promise<StudentMaterialProgress[]> => {
    const r = await api.get(`${BASE_URL}/material-progress/`, { params });
    return r.data.results || r.data;
  },
  get: async (id: number): Promise<StudentMaterialProgress> => {
    const r = await api.get(`${BASE_URL}/material-progress/${id}/`);
    return r.data;
  },
  create: async (data: { material: number }): Promise<StudentMaterialProgress> => {
    const r = await api.post(`${BASE_URL}/material-progress/`, data);
    return r.data;
  },
  update: async (id: number, data: StudentMaterialProgressUpdate): Promise<StudentMaterialProgress> => {
    const r = await api.patch(`${BASE_URL}/material-progress/${id}/`, data);
    return r.data;
  },
  markStarted: async (id: number): Promise<APIResponse> => {
    const r = await api.post(`${BASE_URL}/material-progress/${id}/mark-started/`);
    return r.data;
  },
  markCompleted: async (id: number): Promise<APIResponse> => {
    const r = await api.post(`${BASE_URL}/material-progress/${id}/mark-completed/`);
    return r.data;
  },
  updatePosition: async (data: {
    material_id: number;
    last_position_seconds?: number;
    time_spent_seconds?: number;
    percentage_completed?: number;
  }): Promise<APIResponse> => {
    const r = await api.post(`${BASE_URL}/material-progress/update-position/`, data);
    return r.data;
  },
};

export const pathProgressAPI = {
  list: async (): Promise<StudentLearningPathProgress[]> => {
    const r = await api.get(`${BASE_URL}/path-progress/`);
    return r.data.results || r.data;
  },
  get: async (id: number): Promise<StudentLearningPathProgress> => {
    const r = await api.get(`${BASE_URL}/path-progress/${id}/`);
    return r.data;
  },
  enroll: async (learning_path_id: number): Promise<APIResponse<StudentLearningPathProgress>> => {
    const r = await api.post(`${BASE_URL}/path-progress/enroll/`, { learning_path_id });
    return r.data;
  },
  unlockNext: async (id: number): Promise<APIResponse<StudentLearningPathProgress>> => {
    const r = await api.post(`${BASE_URL}/path-progress/${id}/unlock-next/`);
    return r.data;
  },
};

// ── Annotations & Peer Sharing ────────────────────────────────

export const bookmarksAPI = {
  list: async (): Promise<StudentBookmark[]> => {
    const r = await api.get(`${BASE_URL}/bookmarks/`);
    return r.data.results || r.data;
  },
  get: async (id: number): Promise<StudentBookmark> => {
    const r = await api.get(`${BASE_URL}/bookmarks/${id}/`);
    return r.data;
  },
  create: async (data: StudentBookmarkCreate): Promise<StudentBookmark> => {
    const r = await api.post(`${BASE_URL}/bookmarks/`, data);
    return r.data;
  },
  update: async (id: number, data: Partial<StudentBookmarkCreate>): Promise<StudentBookmark> => {
    const r = await api.patch(`${BASE_URL}/bookmarks/${id}/`, data);
    return r.data;
  },
  delete: async (id: number): Promise<void> => {
    await api.delete(`${BASE_URL}/bookmarks/${id}/`);
  },
};

export const highlightsAPI = {
  list: async (params?: { lesson_note?: number }): Promise<StudentHighlight[]> => {
    const r = await api.get(`${BASE_URL}/highlights/`, { params });
    return r.data.results || r.data;
  },
  get: async (id: number): Promise<StudentHighlight> => {
    const r = await api.get(`${BASE_URL}/highlights/${id}/`);
    return r.data;
  },
  create: async (data: StudentHighlightCreate): Promise<StudentHighlight> => {
    const r = await api.post(`${BASE_URL}/highlights/`, data);
    return r.data;
  },
  update: async (id: number, data: Partial<StudentHighlightCreate>): Promise<StudentHighlight> => {
    const r = await api.patch(`${BASE_URL}/highlights/${id}/`, data);
    return r.data;
  },
  delete: async (id: number): Promise<void> => {
    await api.delete(`${BASE_URL}/highlights/${id}/`);
  },
};

export const sharedNotesAPI = {
  list: async (params?: { subject?: number; status?: string }): Promise<StudentSharedNoteList[]> => {
    const r = await api.get(`${BASE_URL}/shared-notes/`, { params });
    return r.data.results || r.data;
  },
  get: async (id: number): Promise<StudentSharedNoteDetail> => {
    const r = await api.get(`${BASE_URL}/shared-notes/${id}/`);
    return r.data;
  },
  create: async (data: StudentSharedNoteCreate): Promise<StudentSharedNoteDetail> => {
    const r = await api.post(`${BASE_URL}/shared-notes/`, data);
    return r.data;
  },
  update: async (id: number, data: Partial<StudentSharedNoteCreate>): Promise<StudentSharedNoteDetail> => {
    const r = await api.patch(`${BASE_URL}/shared-notes/${id}/`, data);
    return r.data;
  },
  delete: async (id: number): Promise<void> => {
    await api.delete(`${BASE_URL}/shared-notes/${id}/`);
  },
  moderate: async (id: number, data: SharedNoteModerationPayload): Promise<APIResponse> => {
    const r = await api.post(`${BASE_URL}/shared-notes/${id}/moderate/`, data);
    return r.data;
  },
  like: async (id: number): Promise<APIResponse> => {
    const r = await api.post(`${BASE_URL}/shared-notes/${id}/like/`);
    return r.data;
  },
  recordView: async (id: number): Promise<APIResponse> => {
    const r = await api.post(`${BASE_URL}/shared-notes/${id}/view/`);
    return r.data;
  },
};

// ── Live Classes ──────────────────────────────────────────────

export const liveClassesAPI = {
  list: async (params?: { status?: string }): Promise<LiveClassSessionList[]> => {
    const r = await api.get(`${BASE_URL}/live-classes/`, { params });
    return r.data.results || r.data;
  },
  get: async (id: number): Promise<LiveClassSessionDetail> => {
    const r = await api.get(`${BASE_URL}/live-classes/${id}/`);
    return r.data;
  },
  create: async (data: LiveClassSessionCreate): Promise<LiveClassSessionDetail> => {
    const r = await api.post(`${BASE_URL}/live-classes/`, data);
    return r.data;
  },
  update: async (id: number, data: Partial<LiveClassSessionCreate>): Promise<LiveClassSessionDetail> => {
    const r = await api.patch(`${BASE_URL}/live-classes/${id}/`, data);
    return r.data;
  },
  delete: async (id: number): Promise<void> => {
    await api.delete(`${BASE_URL}/live-classes/${id}/`);
  },
  start: async (id: number): Promise<APIResponse<LiveClassSessionDetail>> => {
    const r = await api.post(`${BASE_URL}/live-classes/${id}/start/`);
    return r.data;
  },
  end: async (id: number): Promise<APIResponse> => {
    const r = await api.post(`${BASE_URL}/live-classes/${id}/end/`);
    return r.data;
  },
  join: async (id: number, data?: LiveClassJoinPayload): Promise<APIResponse<LiveClassJoinResponse>> => {
    const r = await api.post(`${BASE_URL}/live-classes/${id}/join/`, data || {});
    return r.data;
  },
  leave: async (id: number): Promise<APIResponse> => {
    const r = await api.post(`${BASE_URL}/live-classes/${id}/leave/`);
    return r.data;
  },
  saveWhiteboard: async (id: number, data: {
    whiteboard_data: Record<string, unknown>;
    title?: string;
  }): Promise<APIResponse<LiveClassWhiteboard>> => {
    const r = await api.post(`${BASE_URL}/live-classes/${id}/save-whiteboard/`, data);
    return r.data;
  },
  getAttendance: async (id: number): Promise<APIResponse<LiveClassAttendance[]>> => {
    const r = await api.get(`${BASE_URL}/live-classes/${id}/attendance/`);
    return r.data;
  },
};

export const liveClassAttendanceAPI = {
  list: async (params?: { live_class?: number }): Promise<LiveClassAttendance[]> => {
    const r = await api.get(`${BASE_URL}/attendance/`, { params });
    return r.data.results || r.data;
  },
  get: async (id: number): Promise<LiveClassAttendance> => {
    const r = await api.get(`${BASE_URL}/attendance/${id}/`);
    return r.data;
  },
};

export const whiteboardsAPI = {
  list: async (params?: { live_class?: number }): Promise<LiveClassWhiteboard[]> => {
    const r = await api.get(`${BASE_URL}/whiteboards/`, { params });
    return r.data.results || r.data;
  },
  get: async (id: number): Promise<LiveClassWhiteboard> => {
    const r = await api.get(`${BASE_URL}/whiteboards/${id}/`);
    return r.data;
  },
};

export const studentScreensAPI = {
  list: async (params?: { live_class?: number }): Promise<StudentScreenMonitor[]> => {
    const r = await api.get(`${BASE_URL}/student-screens/`, { params });
    return r.data.results || r.data;
  },
  get: async (id: number): Promise<StudentScreenMonitor> => {
    const r = await api.get(`${BASE_URL}/student-screens/${id}/`);
    return r.data;
  },
  flag: async (id: number, data: ScreenMonitorFlagPayload): Promise<APIResponse> => {
    const r = await api.post(`${BASE_URL}/student-screens/${id}/flag-screen/`, data);
    return r.data;
  },
};

export const penStreamsAPI = {
  list: async (params?: { live_class?: number }): Promise<LiveClassPenStream[]> => {
    const r = await api.get(`${BASE_URL}/pen-streams/`, { params });
    return r.data.results || r.data;
  },
  get: async (id: number): Promise<LiveClassPenStream> => {
    const r = await api.get(`${BASE_URL}/pen-streams/${id}/`);
    return r.data;
  },
  create: async (data: Partial<LiveClassPenStream>): Promise<LiveClassPenStream> => {
    const r = await api.post(`${BASE_URL}/pen-streams/`, data);
    return r.data;
  },
  update: async (id: number, data: Partial<LiveClassPenStream>): Promise<LiveClassPenStream> => {
    const r = await api.patch(`${BASE_URL}/pen-streams/${id}/`, data);
    return r.data;
  },
  delete: async (id: number): Promise<void> => {
    await api.delete(`${BASE_URL}/pen-streams/${id}/`);
  },
  end: async (id: number): Promise<APIResponse> => {
    const r = await api.post(`${BASE_URL}/pen-streams/${id}/end/`);
    return r.data;
  },
};

export const smartPensAPI = {
  list: async (): Promise<SmartPenDevice[]> => {
    const r = await api.get(`${BASE_URL}/smart-pens/`);
    return r.data.results || r.data;
  },
  get: async (id: number): Promise<SmartPenDevice> => {
    const r = await api.get(`${BASE_URL}/smart-pens/${id}/`);
    return r.data;
  },
  create: async (data: Partial<SmartPenDevice>): Promise<SmartPenDevice> => {
    const r = await api.post(`${BASE_URL}/smart-pens/`, data);
    return r.data;
  },
  update: async (id: number, data: Partial<SmartPenDevice>): Promise<SmartPenDevice> => {
    const r = await api.patch(`${BASE_URL}/smart-pens/${id}/`, data);
    return r.data;
  },
  delete: async (id: number): Promise<void> => {
    await api.delete(`${BASE_URL}/smart-pens/${id}/`);
  },
};

export const handwritingCapturesAPI = {
  list: async (): Promise<HandwritingCapture[]> => {
    const r = await api.get(`${BASE_URL}/handwriting-captures/`);
    return r.data.results || r.data;
  },
  get: async (id: number): Promise<HandwritingCapture> => {
    const r = await api.get(`${BASE_URL}/handwriting-captures/${id}/`);
    return r.data;
  },
  create: async (data: Partial<HandwritingCapture>): Promise<HandwritingCapture> => {
    const r = await api.post(`${BASE_URL}/handwriting-captures/`, data);
    return r.data;
  },
  update: async (id: number, data: Partial<HandwritingCapture>): Promise<HandwritingCapture> => {
    const r = await api.patch(`${BASE_URL}/handwriting-captures/${id}/`, data);
    return r.data;
  },
  delete: async (id: number): Promise<void> => {
    await api.delete(`${BASE_URL}/handwriting-captures/${id}/`);
  },
};

// ============================================================
// SYSTEM INFRASTRUCTURE
// ============================================================

export const aiQueueAPI = {
  list: async (params?: { status?: string; task_type?: string }): Promise<AIProcessingQueue[]> => {
    const r = await api.get(`${BASE_URL}/queue/`, { params });
    return r.data.results || r.data;
  },
  get: async (id: number): Promise<AIProcessingQueue> => {
    const r = await api.get(`${BASE_URL}/queue/${id}/`);
    return r.data;
  },
  summary: async (): Promise<Record<string, number>> => {
    const r = await api.get(`${BASE_URL}/queue/summary/`);
    return r.data.data;
  },
};